const os=require('os')
console.log(os.platform())
console.log(os.uptime())
console.log(os.totalmem())
console.log(os.freemem())
console.log(os.availableParallelism())
console.log(os.userInfo())
console.log(os.networkInterfaces())
